<?php

/**
 * @file
 * Primary module hooks for My Admin Styles module.
 */

use Drupal\Core\Asset\AttachedAssetsInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\core_provetecmar\Controller\QuoteController;
use Drupal\Core\Render\Markup;

/**
 * Implementa hook_form_alter().
 */
function core_provetecmar_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id === 'node_quote_edit_form' || $form_id === 'node_quote_form') {
    $form['field_products']['#prefix'] = '<div class="quote-parameters"></div><div class="quote-messages"></div>';
    if (isset($form['field_products']['widget'])) {
      $settings = [];
      $taxs = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadByProperties([
        'vid' => 'trm_a_usd'
      ]);
      if(!empty($taxs)){
        foreach ($taxs as $key => $tax) {
          $settings['parameters'][] = [
            'name' => $tax->name->value,
            'tid' => $tax->tid->value,
            'factor' => $tax->field_factor->value
          ];
        }
      }

      foreach ($form['field_products']['widget'] as $delta => &$paragraph_item) {
        if (is_numeric($delta) && isset($paragraph_item['subform']['field_product'])) {
          if (!empty($paragraph_item['subform']['field_product']['widget'][0]['target_id']['#default_value'])) {
            $node = $paragraph_item['subform']['field_product']['widget'][0]['target_id']['#default_value'];
            $nid = $node->id();
            if(
              $node->field_unit_weight->value != 0 &&
              $node->field_unit_cost->value != 0 &&
              $node->field_provider->target_id != ''
            ){
              $settings[] = ['nid' => $nid, 'class' => 'product-success'];
            }else{
              $settings[] = ['nid' => $nid, 'class' => 'product-warning'];
            }
            $paragraph_item['#attributes']['class'][] = 'valid-'.$nid;
            $paragraph_item['subform']['field_product']['#prefix'] = '<a data-nid="'.$nid.'" href="/node/' . $nid . '/edit" class="show-product" target="_blank">+</a>';
          }
        }
      }
    }
    $form['field_requests_send']['widget']['#prefix'] = '<div class="loader-overlay" style="display:none;"><div class="spinner"></div></div><a id="send-request" href="#" class="button js-form-submit form-submit">Enviar Solicitudes</a>';
    $form['actions']['submit']['#validate'][] = '_quote_validation_custom';
    $form['actions']['submit']['#submit'][] = '_quote_submit_custom';
    $form['#attached']['drupalSettings']['quote_settings'] = $settings;
    $form['#attached']['library'][] = 'core_provetecmar/quote';
  }
}

/**
 * Validation custom quote
 */
function _quote_validation_custom($form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $form_state->setTemporaryValue('entity_validated', TRUE);
  $node = $form_state->getFormObject()->getEntity();
  $service = \Drupal::service('core_provetecmar.importxlsx_validation');
  $resultImport = $service->importXlsxValidation($node, 'field_items_import');
  if(!$resultImport['success'])
  {
    $form_state->setErrorByName(
      'field_items_import',
      Markup::create('<ul>' . $resultImport['message'] . '</ul>')
    );
  }

  $valQuote = \Drupal::service('core_provetecmar.validate_quote');
  $resultVal = $valQuote->validateQuote($node, $form, $form_state);
  if(!$resultVal['success'])
  {
    foreach ($resultVal['message'] as $value) {
      $form_state->setErrorByName(
        "field_products][{$value['k']}][subform][field_product",
        Markup::create($value['msg'])
      );  
    }
    
  }

}

/**
 * Submit custom quote
 */
function _quote_submit_custom($form, \Drupal\Core\Form\FormStateInterface $form_state) {
  // Ejemplo: obtener el nodo.
  $node = $form_state->getFormObject()->getEntity();
  $service = \Drupal::service('core_provetecmar.importxlsx');
  $resultImport = $service->importXlsx($node, 'field_items_import');
  if(isset($resultImport['success'])){
    if($resultImport['success'])
      \Drupal::messenger()->addStatus($resultImport['message']);
    else{
      $form_state->setErrorByName(
        'field_items_import',
        Markup::create($resultImport['message'])
      );
    }
  }

  $values = $form_state->getValues();
  if (isset($values['field_requests_send']) && $node->field_requests_send->value == 1){
    $sendRequests = \Drupal::service('core_provetecmar.mailsendrequest');
    $sendRequests->proccess($node);
    $node->set('field_requests_send',0);
    $node->save();
  }
}

/**
 * Implements hook_page_attachments().
 */
function core_provetecmar_page_attachments(array &$attachments) {
  $theme_name = \Drupal::theme()->getActiveTheme()->getName();
  if ($theme_name === 'gin') {
    $attachments['#attached']['library'][] = 'core_provetecmar/admin-theme-style';
  }
}

function core_provetecmar_theme($existing, $type, $theme, $path) {
  return [
    'node__quote' => [
      'render element' => 'elements',
      'base hook' => 'node',
      'template' => 'node--quote',
      'path' => \Drupal::service('extension.list.module')->getPath('core_provetecmar') . '/templates',
    ],
    'rfq_mail' => [
      'variables' => [
        'company_name' => NULL,
        'rfq_number' => NULL,
        'data' => NULL,
        'items' => [],
      ],
    ],
    'rfq_pdf_mail' => [
      'variables' => [
        'company_name' => NULL,
        'rfq_number' => NULL,
        'data' => NULL,
        'items' => [],
      ],
    ],
  ];
}

function core_provetecmar_mail($key, &$message, $params) {
  $message['subject'] = $params['subject'] ?? '';
  $message['body'][] = $params['body'] ?? '';
  if (!empty($params['headers']) && is_array($params['headers'])) {
    $message['headers'] = array_merge($message['headers'], $params['headers']);
  }
}


/**
 * Implements hook_node_access().
 */
function core_provetecmar_node_access(\Drupal\node\NodeInterface $node, $op, \Drupal\Core\Session\AccountInterface $account) {
  if ($op === 'update') {
    if ($node->hasField('field_quoter')) {
      $state = $node->get('moderation_state')->value;
      if($state == "assignment"){
        $autores = $node->get('field_quoter')->referencedEntities();
        foreach ($autores as $autor) {
          if ($autor->id() === $account->id()) {
            return \Drupal\Core\Access\AccessResult::allowed()->addCacheableDependency($node);
          }
        }
      }

    }
  }

  return \Drupal\Core\Access\AccessResult::neutral();
}