<?php

/**
 * @file
 * Primary module hooks for My Admin Styles module.
 */

use Drupal\Core\Render\Markup;

/**
 * Implementa hook_form_alter().
 */
function core_provetecmar_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id === 'node_quote_edit_form' || $form_id === 'node_quote_form') {
    $form['field_products']['#access'] = FALSE;
    $form['field_requests_send']['#prefix'] = '<div class="quote-app"><div class="quote-table-wrapper">
  <table class="quote-table">
    <thead>
      <tr>
        <th class="td-small td-check">
          <span>No.</span>
          <div class="check-succ"></div>
        </th>
        <th>Producto</th>
        <th class="td-small">Cantidad</th>
        <th>Peso total</th>
        <th>Total</th>
        <th class="td-medium">Empresa</th>
        <th class="td-medium">Región entrega</th>
        <th>Impuesto (%)</th>
        <th>Costo Unitario USD</th>
        <th>Costo total (USD)</th>
        <th>Gravamen (%)</th>
        <th>Margen (%)</th>
        <th>Incoterm</th>
        <th>Factor cost</th>
        <th class="td-medium">Tipo envío</th>
        <th>Tipo contenedor</th>
        <th>Qty</th>
        <th>Entrega contenedor</th>
        <th>Vr Unitario (USD)</th>
        <th>Vr Total (USD)</th>
        <th>Factor</th>
        <th>Tiempo entrega</th>
        <th>Comentarios</th>
        <th class="td-small">🗑️</th>
      </tr>
    </thead>
    <tbody id="quote-lines">

    </tbody>
  </table>


</div>
<div class="table-actions">
    <button id="add-line" type="button" class="btn btn-add">➕ Agregar línea</button>
  </div>
</div><div class="quote-parameters"></div><div class="quote-messages"></div>';
    $nodeQuote = $form_state->getFormObject()->getEntity();
    $arrState = ['assignment','price_change'];
    if(!empty($nodeQuote->get('moderation_state')->value) && in_array($nodeQuote->get('moderation_state')->value, $arrState) ){
      $form['field_products']['#suffix'] = '<div class="requests-send"><span class="button-primary">Enviar Solicitudes</span></div><div class="quote-modal quote-hide"><div class="loader-overlay" style="display:none;"><div class="spinner"></div></div><div class="quote-modal--body"><div class="quote-modal--head"></div></div></div>';
    }
    if (isset($form['field_products']['widget'])) {
      $settings = [];
      $serviceParam = \Drupal::service('core_provetecmar.parameters_quote');
      $settings = $serviceParam->getParameters();
      $settings['items'] = $serviceParam->getData($nodeQuote);
      $settings['nid'] = $nodeQuote->nid->value;
    }
    $form['actions']['submit']['#validate'][] = '_quote_validation_custom';
    $form['actions']['submit']['#submit'][] = '_quote_submit_custom';
    $arrState = ['assignment','price_change'];
    $settings['process'] = TRUE;
    $arrState = ['published','offer_ready'];
    if(!empty($nodeQuote->get('moderation_state')->value) && in_array($nodeQuote->get('moderation_state')->value, $arrState) ){
      $settings['process'] = FALSE;
    }
    if($form_id === 'node_quote_form'){
      $settings['process'] = -1;
    }
    $form['#attached']['drupalSettings'] = $settings;
    $form['#attached']['library'][] = 'core_provetecmar/quote';
  }
  if ($form_id === 'node_purchase_order_edit_form' || $form_id === 'node_purchase_order_form') {
    $form['#attached']['library'][] = 'core_provetecmar/quote';
  }
}

/**
 * Validation custom quote
 */
function _quote_validation_custom($form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $form_state->setTemporaryValue('entity_validated', TRUE);
  $node = $form_state->getFormObject()->getEntity();
  $service = \Drupal::service('core_provetecmar.importxlsx_validation');
  $resultImport = $service->importXlsxValidation($form, $form_state);
  if(!$resultImport['success'])
  {
    $form_state->setErrorByName(
      'field_items_import',
      Markup::create('<ul>' . $resultImport['message'] . '</ul>')
    );
  }

  $valQuote = \Drupal::service('core_provetecmar.validate_quote');
  $resultVal = $valQuote->validateQuote($node, $form, $form_state);
  if(!$resultVal['success'])
  {
    foreach ($resultVal['message'] as $value) {
      $form_state->setErrorByName(
        "field_products][{$value['k']}][subform][field_product",
        Markup::create($value['msg'])
      );
    }

  }

}

/**
 * Submit custom quote
 */
function _quote_submit_custom($form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $node = $form_state->getFormObject()->getEntity();
  $service = \Drupal::service('core_provetecmar.importxlsx');
  $resultImport = $service->importXlsx($form, $form_state);
  /*if(isset($resultImport['success'])){
    if($resultImport['success'])
      \Drupal::messenger()->addStatus($resultImport['message']);
    else{
      $form_state->setErrorByName(
        'field_items_import',
        Markup::create($resultImport['message'])
      );
    }
  }*/

  $values = $form_state->getValues();
  if (isset($values['field_requests_send']) && $node->field_requests_send->value == 1){
    $sendRequests = \Drupal::service('core_provetecmar.mailsendrequest');
    $sendRequests->proccess($node);
    $node->set('field_requests_send',0);
    $node->save();
  }
}

/**
 * Implements hook_page_attachments().
 */
function core_provetecmar_page_attachments(array &$attachments) {
  $theme_name = \Drupal::theme()->getActiveTheme()->getName();
  if ($theme_name === 'gin') {
    $attachments['#attached']['library'][] = 'core_provetecmar/admin-theme-style';
  }
}

function core_provetecmar_theme($existing, $type, $theme, $path) {
  return [
    'node__quote' => [
      'render element' => 'elements',
      'base hook' => 'node',
      'template' => 'node--quote',
      'path' => \Drupal::service('extension.list.module')->getPath('core_provetecmar') . '/templates',
    ],
    'rfq_mail' => [
      'variables' => [
        'company_name' => NULL,
        'rfq_number' => NULL,
        'data' => NULL,
        'items' => [],
      ],
    ],
    'rfq_pdf_mail' => [
      'variables' => [
        'company_name' => NULL,
        'rfq_number' => NULL,
        'data' => NULL,
        'items' => [],
      ],
    ],
    'quote_pdf' => [
      'variables' => [
        'data' => NULL,
        'items' => [],
      ],
    ],
    'node__purchase_order' => [
      'variables' => [
        'render element' => 'elements',
        'base hook' => 'node',
        'template' => 'node--purchase-order',
        'path' => \Drupal::service('extension.list.module')->getPath('core_provetecmar') . '/templates',
      ],
    ],
    'purchase_order_pdf' => [
      'variables' => [
        'data' => NULL,
        'items' => [],
      ],
    ],
  ];
}

function core_provetecmar_mail($key, &$message, $params) {
  $message['subject'] = $params['subject'] ?? '';
  $message['body'][] = $params['body'] ?? '';
  if (!empty($params['headers']) && is_array($params['headers'])) {
    $message['headers'] = array_merge($message['headers'], $params['headers']);
  }
}


/**
 * Implements hook_node_access().
 */
function core_provetecmar_node_access(\Drupal\node\NodeInterface $node, $op, \Drupal\Core\Session\AccountInterface $account) {
  if ($op === 'update') {
    if ($node->hasField('field_quoter')) {
      $state = $node->get('moderation_state')->value;
      if($state == "assignment"){
        $autores = $node->get('field_quoter')->referencedEntities();
        foreach ($autores as $autor) {
          if ($autor->id() === $account->id()) {
            return \Drupal\Core\Access\AccessResult::allowed()->addCacheableDependency($node);
          }
        }
      }

    }
  }

  return \Drupal\Core\Access\AccessResult::neutral();
}

/**
 * Implements hook_node_access().
 */
function core_provetecmar_preprocess_node(array &$variables) {
  $node = $variables['node'];
  $account = \Drupal::currentUser();
  $can_edit = $node->access('update', $account);
  $variables['can_edit'] = $can_edit;
}
